#!/usr/bin/env bash

base_dir=$(dirname "$0")

if [[ "#grep#fetch#cleanup#diff#" != *"#$1#"* ]]; then
  "$base_dir"/update_depends
fi

PYTHONDONTWRITEBYTECODE=1 exec python "$base_dir/depends.py" "$@"
